name: quest-compose

services:
  java:
    image: quest-java:latest
    
    # Pour utiliser un Dockerfile (Docker fera un Docker Build)
    # build:
    #   content: quest-boot # Le nom du répertoire dans lequel se trouve le fichier Dockerfile

    container_name: quest-boot
    ports:
      - 8090:8080
    environment:
      ENV_DB_URL: mysql://db:3306/quest_boot
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quest

  db:
    image: mysql:latest
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: Y
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - quest

volumes:
  db_data:

networks:
  quest:
